-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 17:27:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `Biblioteca` ;

-- -----------------------------------------------------
-- Table `Biblioteca`.`Libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Biblioteca`.`Libros` ;

CREATE TABLE IF NOT EXISTS `Biblioteca`.`Libros` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Editorial` VARCHAR(45) NOT NULL,
  `Area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Biblioteca`.`Autores` ;

CREATE TABLE IF NOT EXISTS `Biblioteca`.`Autores` (
  `idAutor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteca`.`LibroAutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Biblioteca`.`LibroAutores` ;

CREATE TABLE IF NOT EXISTS `Biblioteca`.`LibroAutores` (
  `idLibro` INT NOT NULL,
  `idAutor` INT NOT NULL,
  PRIMARY KEY (`idLibro`, `idAutor`),
  INDEX `fk_Libro_has_Autor_Autor1_idx` (`idAutor` ASC) VISIBLE,
  INDEX `fk_Libro_has_Autor_Libro1_idx` (`idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_Libro_has_Autor_Libro1`
    FOREIGN KEY (`idLibro`)
    REFERENCES `Biblioteca`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_has_Autor_Autor1`
    FOREIGN KEY (`idAutor`)
    REFERENCES `Biblioteca`.`Autores` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Biblioteca`.`Estudiantes` ;

CREATE TABLE IF NOT EXISTS `Biblioteca`.`Estudiantes` (
  `idLector` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Carrera` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  PRIMARY KEY (`idLector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Biblioteca`.`Prestamos` ;

CREATE TABLE IF NOT EXISTS `Biblioteca`.`Prestamos` (
  `FechaPrestamo` DATETIME NOT NULL,
  `FechaDevolucion` DATETIME NOT NULL,
  `Devuelto` TINYINT NULL,
  `Prestamocol` VARCHAR(45) NULL,
  `idLector` INT NOT NULL,
  `idLibro` INT NOT NULL,
  INDEX `idLibro_idx` (`idLibro` ASC) VISIBLE,
  INDEX `idLector_idx` (`idLector` ASC) VISIBLE,
  PRIMARY KEY (`idLibro`, `idLector`),
  CONSTRAINT `idLector`
    FOREIGN KEY (`idLector`)
    REFERENCES `Biblioteca`.`Estudiantes` (`idLector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idLibro`
    FOREIGN KEY (`idLibro`)
    REFERENCES `Biblioteca`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
