-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 12:47:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Empresa_Internet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Empresa_Internet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Empresa_Internet` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `Empresa_Internet` ;

-- -----------------------------------------------------
-- Table `Empresa_Internet`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa_Internet`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nombre` VARCHAR(30) NULL,
  `apellido` VARCHAR(30) NULL,
  `dni` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa_Internet`.`Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa_Internet`.`Plan` (
  `idPlan` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `AnchoBanda` VARCHAR(45) NULL,
  `Plancol` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa_Internet`.`Paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa_Internet`.`Paquete` (
  `idPaquete` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Plan_idPlan` INT NOT NULL,
  PRIMARY KEY (`idPaquete`),
  INDEX `fk_Paquete_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Paquete_Plan1_idx` (`Plan_idPlan` ASC) VISIBLE,
  CONSTRAINT `fk_Paquete_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `Empresa_Internet`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paquete_Plan1`
    FOREIGN KEY (`Plan_idPlan`)
    REFERENCES `Empresa_Internet`.`Plan` (`idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa_Internet`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa_Internet`.`Direccion` (
  `idDireccion` INT NOT NULL,
  `calle` VARCHAR(30) NULL,
  `Numero` INT NULL,
  `Localidad` VARCHAR(30) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idDireccion`),
  INDEX `fk_Direccion_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `Empresa_Internet`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Empresa_Internet` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `Empresa_Internet`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
