-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 10:10:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proveedor_internet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proveedor_internet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proveedor_internet` DEFAULT CHARACTER SET utf8 ;
USE `proveedor_internet` ;

-- -----------------------------------------------------
-- Table `proveedor_internet`.`Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proveedor_internet`.`Plan` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `velocidad` INT UNSIGNED NOT NULL,
  `precio` DECIMAL(6,2) UNSIGNED NOT NULL,
  `descuento` DECIMAL(6,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proveedor_internet`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proveedor_internet`.`Cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_de_nacimiento` DATETIME NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `cuidad` VARCHAR(45) NOT NULL,
  `Plan_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `Plan_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  INDEX `fk_Cliente_Plan_idx` (`Plan_id` ASC),
  CONSTRAINT `fk_Cliente_Plan`
    FOREIGN KEY (`Plan_id`)
    REFERENCES `proveedor_internet`.`Plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;