spring:
  h2:
    console:
      enabled: true
      path: /h2A

  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:showroom
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  servlet:
    context-path: /api